-- Padyarchana seed data (reference rows only — NO poems).
-- Run after schema.sql; then run scripts/import_json.py over
-- padyalu_json_data/*.json to repopulate poems.

BEGIN TRANSACTION;

-- meters: 210 rows
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (1, 'ఆటవెలది', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (3, 'Unknown', NULL, 'Meter not specified - requires classification', NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (5, 'సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (6, 'శార్దూలవిక్రీడితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (7, 'మత్తేభవిక్రీడితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (8, 'ఉత్పలమాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (9, 'చంపకమాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (30, 'లయవిభాతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (31, 'వచనము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (33, 'మాలిని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (34, 'గద్యము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (38, 'సీసము + తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (41, 'కందము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (44, 'ఆటవెలది/తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (46, 'తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (47, 'ద్విపద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (48, 'సీసము + ఆటవెలది', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (49, 'తరళము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (51, 'మత్తకోకిల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (52, 'భుజంగప్రయాతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (54, 'తగణ దండకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (55, 'కవిరాజవిరాజితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (56, 'మంగళమహశ్రీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (57, 'స్రగ్ధర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (58, 'ఇంద్రవజ్రము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (59, 'లయగ్రాహి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (60, 'వనమయూరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (61, 'ఉత్సాహము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (62, 'మహాస్రగ్ధర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (63, 'స్రగ్విణీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (64, 'తోటకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (65, 'మానిని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (66, 'ఉపేంద్రవజ్రము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (67, 'పంచచామరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (68, 'సర్వలఘుసీసము + తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (69, 'తరలము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (70, 'గీతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (71, 'శ్లోకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (72, 'వృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (73, 'unknown', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (74, 'ద్విరదగతి రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (75, 'రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (76, 'శ్రీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (77, 'స్త్రీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (78, 'వినయం', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (79, 'బింబము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (80, 'సుకాంతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (81, 'అంబుజ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (82, 'పంక్తి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (83, 'తనుమధ్య', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (84, 'మధుమతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (85, 'మదరేఖ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (86, 'విద్యున్మాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (87, 'చిత్రపదము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (88, 'ప్రమాణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (89, 'హలముఖి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (90, 'రుగ్మవతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (91, 'మత్త', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (92, 'ప్రణవము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (93, 'మయూరసారి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (94, 'శుద్ధవిరాటి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (95, 'మణిరంగము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (96, 'తోదకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (97, 'ఇంద్రవజ్ర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (98, 'ఉపేంద్రవజ్ర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (99, 'ఉపజాతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (100, 'రథోద్ధతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (101, 'గీతాలంబనము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (102, 'స్వాగతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (103, 'శాలిని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (104, 'శ్యేని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (105, 'వాతోర్మి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (106, 'చంద్రిక', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (107, 'తోవకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (108, 'స్రగ్విణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (109, 'ఇంద్రవంశము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (110, 'వంశస్థము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (111, 'ద్రుతవిలంబితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (112, 'జలధరమాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (113, 'ప్రియంవద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (114, 'ప్రమితాక్షరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (115, 'జలోద్ధతగతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (116, 'విశ్వదేవి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (117, 'మత్తమయూరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (118, 'జలదము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (119, 'మంజుభాషిణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (120, 'ప్రహర్షిణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (121, 'ప్రభాతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (122, 'రుచిరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (123, 'వసంత తిలకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (124, 'ప్రహరణ కలిత', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (125, 'సుందరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (126, 'అపరాజితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (127, 'అసంబాధ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (128, 'భూనుతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (129, 'కమల విలసితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (130, 'మణిగణనికరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (131, 'సుకేసరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (132, 'మణిభూషణము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (133, 'మనోజ్ఞ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (134, 'ప్రియకాంత', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (135, 'పద్మకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (136, 'ఫలసదనము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (137, 'చంద్రశ్రీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (138, 'మేదిని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (139, 'నర్కుటము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (140, 'శిఖరిణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (141, 'మందాక్రాంత', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (142, 'పాలాశదళము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (143, 'పృథ్వి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (144, 'హరిణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (145, 'కుసుమితలతావేల్లిత', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (146, 'మేఘవిస్ఫూర్జితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (147, 'భూతిలకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (148, 'చంద్రకళ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (149, 'అంబురుహము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (150, 'ఖచరప్లుతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (151, 'వనమంజరి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (152, 'మణిమాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (153, 'లాటీవిటము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (154, 'భద్రకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (155, 'అశ్వలలితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (156, 'పద్మనాభము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (157, 'అష్టమూర్తి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (158, 'సరసిజము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (159, 'క్రౌంచపదము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (160, 'బంధురము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (161, 'భాస్కర విలసితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (162, 'భుజంగ విజృంభిత', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (163, 'మంగళమహాశ్రీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (164, 'నారీప్లుతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (165, 'మనోహరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (166, 'అంగజాస్త్రము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (167, 'వరాంగి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (168, 'నదీప్రఘోషము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (169, 'శ్రీరమణము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (170, 'రథగమన మనోహరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (171, 'వీణారచనము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (172, 'లయహారి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (173, 'త్రిభంగి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (174, 'దండకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (175, 'ఎత్తుగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (176, 'పవడగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (177, 'మేలనగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (178, 'సమ సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (179, 'ప్రాస సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (180, 'వృత్తప్రాససీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (181, 'సర్వతఃప్రాససీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (182, 'అక్కిలిప్రాస సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (183, 'వడిసీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (184, 'అక్కిలివడిసీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (185, 'అవకలిప్రాస సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (186, 'ఉత్సాహ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (187, 'సర్వలఘుసీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (188, 'తరువోజ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (189, 'మహాక్కర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (190, 'మధ్యాక్కరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (191, 'మధురాక్కరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (192, 'అంతరాక్కరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (193, 'అల్పాక్కర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (194, 'షట్పదము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (195, 'త్రిపద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (196, 'మంజరీ ద్విపద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (197, 'చౌపద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (198, 'వితాళ(చౌపద)ము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (199, 'హయప్రచార రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (200, 'తురగవల్గన రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (201, 'విజయమంగళ రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (202, 'జయభద్ర రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (203, 'మధురగతి రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (204, 'హరిగతి రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (205, 'వృషభగమన రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (206, 'హరిణగతి రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (207, 'మధ్యాక్కర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (208, '5.2', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (209, '5.3', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (210, '5.4', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (211, 'షట్పాదగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (212, 'చూర్ణిక', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (213, 'మత్తేభగర్భిత సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (214, 'సుగంధివృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (215, 'పృథ్వీవృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (216, 'తోదకవృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (217, 'నిరోష్ఠ్యసీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (218, 'తోటకవృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (219, 'పణవవృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (220, 'తరల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (221, 'వృషభగతి రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (222, 'కమలవిలసిత', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (223, 'ఉత్సాహ(సుగంధి)', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (224, 'వినుము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (225, 'భుజంగ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (226, 'తోటక', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (227, 'ద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (228, 'గణసమక దండకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (229, 'ము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (230, 'అనులోమ విలోమ క', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (231, 'పాదభ్రమక క', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (232, 'గోమూత్రికా బంధ క', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (233, 'నాగ బంధ చ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (234, 'ఛురికా బంధ క', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (235, 'చక్ర బంధ శా', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (236, 'ద్వ్యక్షరి క', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (237, 'భుజంగప్రయాతగర్భ స్రగ్విణి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (238, 'మంజరి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (239, 'విజయ మంగళము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (240, 'ప్రభువృత్తము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (241, 'మందారదామ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (242, 'తాళ రగడ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (243, 'కవిరాజ విరాజితము', NULL, NULL, NULL, NULL);

-- poets: 110 rows
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (1, 'వేమన', NULL, NULL, 'క్రీ.శ 1652 – 1730 (సుమారు)', 1652, 1730, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (3, 'బద్దెన భూపాలుడు', 'Baddena Bhupaaludu', NULL, 'క్రీ.శ 1220 – 1280', 1220, 1280, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (4, 'దుర్భా సుబ్రహ్మణ్యశర్మ', NULL, NULL, '1931', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (5, 'మేకా బాపన్న', NULL, NULL, 'క్రీ.శ 19వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (6, 'దాసరి అంజదాసు', NULL, NULL, '1932', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (7, 'Unknown', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (8, 'అలపాటి వెంకటప్పయ్య', NULL, NULL, 'null', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (9, 'సరికొండ నరసింహరాజు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (10, 'బళ్ళ రామచంద్రరాజు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (11, 'అబ్బరాజు పిచ్చయ్య', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (12, 'వాసా కృష్ణమూర్తి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (13, 'కూచిమంచి జగన్నాథ కవి', NULL, NULL, 'క్రీ.శ 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (14, 'కూచిమంచి తిమ్మకవి', NULL, NULL, 'క్రీ.శ 1759 – 1817 (సుమారు)', 1759, 1817, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (15, 'భర్తృహరి', NULL, NULL, 'క్రీ.శ 5వ శతాబ్దం (సంస్కృత కవి)', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (16, 'దేవరకొండ అనంతరావు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (17, 'రచయిత తెలియదు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (18, 'నారాయణం రామానుజాచార్యులు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (19, 'పాలకురికి సోమనాథుడు', NULL, NULL, 'క్రీ.శ 1160 – 1240', 1160, 1240, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (20, 'కంచెర్ల గోపన్న (భక్త రామదాసు)', NULL, NULL, 'క్రీ.శ 1620 – 1688', 1620, 1688, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (21, 'శ్రీ వేదాంతాచార్య', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (22, 'చల్లా పిచ్చయ్య', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (23, 'త్రిపురనేని రామస్వామి', NULL, NULL, 'క్రీ.శ 1887 – 1943', 1887, 1943, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (24, 'ఆదిభట్ట శ్రీరామమూర్తి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (25, 'మట్టపర్తి నడవపల్లి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (26, 'ప్రహరాజు గంగరాజు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (27, 'గోవర్ధనం శ్రీరంగాచార్యులు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (28, 'దాసు శ్రీరాములు', NULL, NULL, 'క్రీ.శ 1846 – 1908', 1846, 1908, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (29, 'మాటూరు వెంకటేశం', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (30, 'బాణాలవవీరశరభయ్య', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (31, 'కుందవరపు కవి చౌడప్ప', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (32, 'వంకాయలపాటి వేంకటకవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (33, 'కూచిమంచి సోమసుందరకవి', NULL, NULL, 'క్రీ.శ 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (34, 'దువ్వూరి రామిరెడ్డి', NULL, NULL, 'క్రీ.శ 1895 – 1947', 1895, 1947, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (35, 'కపిల కృష్ణశర్మ (కర్మశ్రీ)', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (36, 'సుబ్రహ్మణ్య భాగవతులు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (38, 'ఫక్కి అప్పల నరసింహ', NULL, NULL, 'క్రీ.శ 1860 (జన్మ) – 20వ శతాబ్దం ప్రారంభం', 1860, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (39, 'బక్కికులుఁడు వేంకట నరసింహకవీంద్రుఁడు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (40, 'రాళ్ళబండి రాజయ్య కవి', NULL, NULL, '1938', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (41, 'పరవస్తు మునినాథకవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (42, 'పోలిపెద్ది వేంకటరాయకవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (43, 'గోపినాథ వేంకటకవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (44, 'విశ్వనాధ సత్యనారాయణ', NULL, NULL, 'క్రీ.శ 1895 – 1976', 1895, 1976, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (45, 'మాతూరి అప్పావు మొదలారి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (46, 'మాదిరాజు రామకోటీశ్వర శాస్త్రి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (47, 'శేషప్ప కవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (48, 'శేషాచలదాసు (శేషప్ప)', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (49, 'అయ్యల్రాజు త్రిపురాంతక కవి', NULL, NULL, 'క్రీ.శ 16వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (50, 'కట్టా అచ్చయ్యకవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (51, 'ఉన్నవ యోగానందకవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (52, 'కూచి నరసింహము', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (53, 'చెరుకు రామ్మోహన రావు', NULL, NULL, '20వ శతాబ్దం (సమకాలీన)', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (54, 'సదానంద యోగి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (55, 'చేబ్రోలు సరస్వతీదేవి', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (56, 'యథావాక్కుల అన్నమయ్య', NULL, NULL, 'క్రీ.శ 1242 – 1323', 1242, 1323, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (57, 'డా॥ రాధశ్రీ', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (58, 'పరమానంద యతీంద్రుడు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (59, 'శ్రీమతి కల్లూరి విశాలాక్షమ్మ', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (60, 'పరశురామ నృసింహదాసు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (61, 'మంచిరాజు సీతమాంబ', NULL, NULL, '1934', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (62, 'తిరుమడ్యం దిగవింటి నారాయణదాసు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (63, 'మయూరుడు', NULL, NULL, 'క్రీ.శ 7వ శతాబ్దం (సంస్కృత కవి)', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (64, 'దాసు రాముఁడు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (65, 'నారసింహరావు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (66, 'గుమ్మా సాంబశివరావు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (68, 'వేముల పల్లి రాముడు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (69, 'పప్పు మల్లికార్జునరావు', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (70, 'తాళ్ళపాక తిమ్మయ్య', NULL, NULL, 'క్రీ.శ 16వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (71, 'తాళ్లపాక అన్నమాచార్య', NULL, NULL, 'క్రీ.శ 1408 – 1503', 1408, 1503, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (72, 'హరి బ్రహ్మేశ్వర', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (73, 'సన్యాసి', NULL, NULL, 'క్రీ.శ 1861 (జన్మ) – 20వ శతాబ్దం ప్రారంభం', 1861, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (74, 'కొల్లూరు అవతారశర్మ', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (75, 'తరిగొండ వెంగమాంబ', NULL, NULL, 'క్రీ.శ 1730 – 1817', 1730, 1817, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (76, 'తాళ్ళపాక చిన తిరువేంగళనాథుడు', NULL, NULL, 'క్రీ.శ 16వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (77, 'పాల్కురికి సోమనాథుడు', NULL, NULL, 'క్రీ.శ 1160 – 1240', 1160, 1240, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (78, 'మడికి సింగన', NULL, NULL, 'క్రీ.శ 15వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (79, 'శ్రీనాథభట్ట', NULL, NULL, 'క్రీ.శ 13వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (80, 'కూచిమంచి తిమ్మన', NULL, NULL, 'క్రీ.శ 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (81, 'రత్నాకరము గోపాలరాజు', NULL, NULL, 'క్రీ.శ 17వ – 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (82, 'శ్రేష్ఠలూరి వేంకటార్య', NULL, NULL, 'క్రీ.శ 17వ – 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (83, 'కట్టా వరదరాజు', NULL, NULL, 'క్రీ.శ 14వ – 15వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (84, 'గోన బుద్ధారెడ్డి', NULL, NULL, 'క్రీ.శ 13వ శతాబ్దం (1294–1300 సుమారు)', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (85, 'బమ్మెర పోతన', NULL, NULL, 'క్రీ.శ 1450 – 1510', 1450, 1510, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (86, 'నన్నయ, తిక్కన, ఎర్రాప్రెగడ', NULL, NULL, 'క్రీ.శ 11వ – 14వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (87, 'వినుకొండ వల్లభరాయుడు', NULL, NULL, 'క్రీ.శ 14వ – 15వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (88, 'సముఖము వేంకట కృష్ణప్ప నాయకుడు', NULL, NULL, 'క్రీ.శ 1901 (జన్మ) – 20వ శతాబ్దం ప్రారంభం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (89, 'సురభి మాధవ రాయలు', NULL, NULL, '1982', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (90, 'కృష్ణమాచార్యుఁడు', NULL, NULL, '1950', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (91, 'గోపీనాథము వేంకటకవి', NULL, NULL, '1923', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (92, 'గణపవరపు వెంకటకవి', NULL, NULL, '1977', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (93, 'ముద్దుపళని', NULL, NULL, 'క్రీ.శ 1730 – 1790', 1730, 1790, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (94, 'శ్రీనాథుడు', NULL, NULL, 'క్రీ.శ 1365 – 1441', 1365, 1441, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (95, 'తాళ్ళపాక తిరువేంగళప్ప', NULL, NULL, 'క్రీ.శ 16వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (96, 'తాళ్ళపాక పెదతిరుమలాచార్యులు', NULL, NULL, 'క్రీ.శ 16వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (97, 'ఆసూరి మఱింగంటి వేంకట నరసింహాచార్యులు', NULL, NULL, '1980', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (98, 'తరిగొండ వేంగమాంబ', NULL, NULL, 'క్రీ.శ 1730 – 1817', 1730, 1817, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (99, 'కాసుల పురుషోత్తమకవి', NULL, NULL, 'క్రీ.శ 1791 (జన్మ) – 19వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (100, 'శ్రీమతి కామేశ్వరమ్మ', NULL, NULL, '20వ శతాబ్దం', NULL, NULL, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (101, 'అనంతామాత్యుడు', NULL, NULL, 'క్రీ.శ 14వ – 15వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (102, 'లింగమగుంట తిమ్మకవి', NULL, NULL, 'క్రీ.శ 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (103, 'పైడిపాటి లక్ష్మణకవి', NULL, NULL, 'క్రీ.శ 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (104, 'అడిదము సూరకవి', NULL, NULL, 'క్రీ.శ 18వ – 19వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (105, 'కస్తూరి రంగకవి', NULL, NULL, 'క్రీ.శ 17వ – 18వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (106, 'ఆతుకూరి మొల్ల', NULL, NULL, 'క్రీ.శ 15వ – 16వ శతాబ్దం (1440–1530 సుమారు)', 1440, 1530, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (107, 'కంకంటి పాపరాజు', NULL, NULL, 'క్రీ.శ 17వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (108, 'రాయప్రోలు సుబ్బారావు', NULL, NULL, 'క్రీ.శ 1892 – 1984', 1892, 1984, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (109, 'అల్లసాని పెద్దన', NULL, NULL, 'క్రీ.శ 1475 – 1535', 1475, 1535, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (110, 'చేమకూర వేంకటకవి', NULL, NULL, 'క్రీ.శ 17వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (111, 'ముక్కు తిమ్మన', NULL, NULL, 'క్రీ.శ 16వ శతాబ్దం', NULL, NULL, 0);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (112, 'మధునాపంతుల సత్యనారాయణ శాస్త్రి', NULL, NULL, 'క్రీ.శ 1903 – 1991', 1903, 1991, 1);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year, copyright_protected) VALUES (113, 'కట్టమంచి రామలింగారెడ్డి', NULL, NULL, 'క్రీ.శ 1880 – 1951', 1880, 1951, 0);

COMMIT;
