-- Padyarchana seed data (reference rows only — NO poems).
-- Run after schema.sql; then run scripts/import_json.py over
-- padyalu_json_data/*.json to repopulate poems.

BEGIN TRANSACTION;

-- meters: 39 rows
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (1, 'ఆటవెలది', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (3, 'Unknown', NULL, 'Meter not specified - requires classification', NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (5, 'సీసము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (6, 'శార్దూలవిక్రీడితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (7, 'మత్తేభవిక్రీడితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (8, 'ఉత్పలమాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (9, 'చంపకమాల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (30, 'లయవిభాతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (31, 'వచనము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (33, 'మాలిని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (34, 'గద్యము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (38, 'సీసము + తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (41, 'కందము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (44, 'ఆటవెలది/తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (46, 'తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (47, 'ద్విపద', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (48, 'సీసము + ఆటవెలది', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (49, 'తరళము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (51, 'మత్తకోకిల', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (52, 'భుజంగప్రయాతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (54, 'తగణ దండకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (55, 'కవిరాజవిరాజితము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (56, 'మంగళమహశ్రీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (57, 'స్రగ్ధర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (58, 'ఇంద్రవజ్రము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (59, 'లయగ్రాహి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (60, 'వనమయూరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (61, 'ఉత్సాహము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (62, 'మహాస్రగ్ధర', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (63, 'స్రగ్విణీ', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (64, 'తోటకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (65, 'మానిని', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (66, 'ఉపేంద్రవజ్రము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (67, 'పంచచామరము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (68, 'సర్వలఘుసీసము + తేటగీతి', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (69, 'తరలము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (70, 'గీతము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (71, 'శ్లోకము', NULL, NULL, NULL, NULL);
INSERT INTO meters (id, name, name_english, description, gana_structure, example_pattern) VALUES (72, 'వృత్తము', NULL, NULL, NULL, NULL);

-- poets: 97 rows
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (1, 'వేమన', NULL, NULL, '1652', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (3, 'బద్దెన భూపాలుడు', 'Baddena Bhupaaludu', NULL, '1220 - 1280', 1220, 1280);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (4, 'దుర్భా సుబ్రహ్మణ్యశర్మ', NULL, NULL, '1931', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (5, 'మేకా బాపన్న', NULL, NULL, '1850', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (6, 'దాసరి అంజదాసు', NULL, NULL, '1932', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (7, 'Unknown', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (8, 'అలపాటి వెంకటప్పయ్య', NULL, NULL, 'null', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (9, 'సరికొండ నరసింహరాజు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (10, 'బళ్ళ రామచంద్రరాజు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (11, 'అబ్బరాజు పిచ్చయ్య', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (12, 'వాసా కృష్ణమూర్తి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (13, 'కూచిమంచి జగన్నాథ కవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (14, 'కూచిమంచి తిమ్మకవి', NULL, NULL, '1759', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (15, 'భర్తృహరి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (16, 'దేవరకొండ అనంతరావు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (17, 'రచయిత తెలియదు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (18, 'నారాయణం రామానుజాచార్యులు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (19, 'పాలకురికి సోమనాథుడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (20, 'కంచెర్ల గోపన్న (భక్త రామదాసు)', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (21, 'శ్రీ వేదాంతాచార్య', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (22, 'చల్లా పిచ్చయ్య', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (23, 'త్రిపురనేని రామస్వామి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (24, 'ఆదిభట్ట శ్రీరామమూర్తి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (25, 'మట్టపర్తి నడవపల్లి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (26, 'ప్రహరాజు గంగరాజు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (27, 'గోవర్ధనం శ్రీరంగాచార్యులు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (28, 'దాసు శ్రీరాములు', NULL, NULL, '1894', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (29, 'మాటూరు వెంకటేశం', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (30, 'బాణాలవవీరశరభయ్య', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (31, 'కుందవరపు కవి చౌడప్ప', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (32, 'వంకాయలపాటి వేంకటకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (33, 'కూచిమంచి సోమసుందరకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (34, 'దువ్వూరి రామిరెడ్డి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (35, 'కపిల కృష్ణశర్మ (కర్మశ్రీ)', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (36, 'సుబ్రహ్మణ్య భాగవతులు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (38, 'ఫక్కి అప్పల నరసింహ', NULL, NULL, '1860', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (39, 'బక్కికులుఁడు వేంకట నరసింహకవీంద్రుఁడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (40, 'రాళ్ళబండి రాజయ్య కవి', NULL, NULL, '1938', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (41, 'పరవస్తు మునినాథకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (42, 'పోలిపెద్ది వేంకటరాయకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (43, 'గోపినాథ వేంకటకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (44, 'విశ్వనాధ సత్యనారాయణ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (45, 'మాతూరి అప్పావు మొదలారి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (46, 'మాదిరాజు రామకోటీశ్వర శాస్త్రి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (47, 'శేషప్ప కవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (48, 'శేషాచలదాసు (శేషప్ప)', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (49, 'అయ్యల్రాజు త్రిపురాంతక కవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (50, 'కట్టా అచ్చయ్యకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (51, 'ఉన్నవ యోగానందకవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (52, 'కూచి నరసింహము', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (53, 'చెరుకు రామ్మోహన రావు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (54, 'సదానంద యోగి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (55, 'చేబ్రోలు సరస్వతీదేవి', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (56, 'యథావాక్కుల అన్నమయ్య', NULL, NULL, '1242', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (57, 'డా॥ రాధశ్రీ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (58, 'పరమానంద యతీంద్రుడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (59, 'శ్రీమతి కల్లూరి విశాలాక్షమ్మ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (60, 'పరశురామ నృసింహదాసు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (61, 'మంచిరాజు సీతమాంబ', NULL, NULL, '1934', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (62, 'తిరుమడ్యం దిగవింటి నారాయణదాసు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (63, 'మయూరుడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (64, 'దాసు రాముఁడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (65, 'నారసింహరావు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (66, 'గుమ్మా సాంబశివరావు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (68, 'వేముల పల్లి రాముడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (69, 'పప్పు మల్లికార్జునరావు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (70, 'తాళ్ళపాక తిమ్మయ్య', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (71, 'తాళ్లపాక అన్నమాచార్య', NULL, NULL, 'క్రీ.శ 1408 మే 9 - 1503 ఫిబ్రవరి 23', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (72, 'హరి బ్రహ్మేశ్వర', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (73, 'సన్యాసి', NULL, NULL, '1861', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (74, 'కొల్లూరు అవతారశర్మ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (75, 'తరిగొండ వెంగమాంబ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (76, 'తాళ్ళపాక చిన తిరువేంగళనాథుడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (77, 'పాల్కురికి సోమనాథుడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (78, 'మడికి సింగన', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (79, 'శ్రీనాథభట్ట', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (80, 'కూచిమంచి తిమ్మన', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (81, 'రత్నాకరము గోపాలరాజు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (82, 'శ్రేష్ఠలూరి వేంకటార్య', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (83, 'కట్టా వరదరాజు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (84, 'గోన బుద్ధారెడ్డి', NULL, NULL, 'క్రీ.శ 1294 - 1300', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (85, 'బమ్మెర పోతన', NULL, NULL, 'క్రీ.శ 1450 - 1510', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (86, 'నన్నయ, తిక్కన, ఎర్రాప్రెగడ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (87, 'వినుకొండ వల్లభరాయుడు', NULL, NULL, NULL, NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (88, 'సముఖము వేంకట కృష్ణప్ప నాయకుడు', NULL, NULL, '1901', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (89, 'సురభి మాధవ రాయలు', NULL, NULL, '1982', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (90, 'కృష్ణమాచార్యుఁడు', NULL, NULL, '1950', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (91, 'గోపీనాథము వేంకటకవి', NULL, NULL, '1923', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (92, 'గణపవరపు వెంకటకవి', NULL, NULL, '1977', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (93, 'ముద్దుపళని', NULL, NULL, '1953', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (94, 'శ్రీనాథుడు', NULL, NULL, 'క్రీ.శ 1365 - 1441', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (95, 'తాళ్ళపాక తిరువేంగళప్ప', NULL, NULL, '16వ శతాబ్దం', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (96, 'తాళ్ళపాక పెదతిరుమలాచార్యులు', NULL, NULL, '16వ శతాబ్దం', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (97, 'ఆసూరి మఱింగంటి వేంకట నరసింహాచార్యులు', NULL, NULL, '1980', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (98, 'తరిగొండ వేంగమాంబ', NULL, NULL, '2007', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (99, 'కాసుల పురుషోత్తమకవి', NULL, NULL, 'క్రీ.శ 1791', NULL, NULL);
INSERT INTO poets (id, name, name_english, biography, era, birth_year, death_year) VALUES (100, 'శ్రీమతి కామేశ్వరమ్మ', NULL, NULL, '20వ శతాబ్దం', NULL, NULL);

COMMIT;
