"""
Dump padyarchana.db into two small, git-friendly SQL files:

  schema.sql  — full DDL (tables, indexes, triggers, FTS5 virtual table).
                Run this first against an empty SQLite file.
  seed.sql    — reference rows for non-bulk tables (meters, poets).
                Run after schema.sql.

The 117k+ poem rows are NOT dumped; they're regenerated by running
`scripts/import_json.py` over `padyalu_json_data/*.json`. That keeps both
files under ~100 KB and avoids putting hundreds of MB of derived data
into git history.

Full rebuild path from a git-only checkout:

    rm -f padyarchana.db                       # if a stale DB exists
    sqlite3 padyarchana.db < schema.sql        # tables + indexes + FTS5
    sqlite3 padyarchana.db < seed.sql          # meters + poets reference rows
    for f in padyalu_json_data/*.json; do
      ./venv/bin/python scripts/import_json.py "$f" --skip-duplicate-check
    done
    ./venv/bin/python scripts/setup_fts5_search.py   # rebuilds FTS5 index

Re-run this script after any schema migration or new meter/poet to
refresh the dumps in git.
"""
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DB = ROOT / "padyarchana.db"
SCHEMA_OUT = ROOT / "schema.sql"
SEED_OUT = ROOT / "seed.sql"

# Tables whose rows are small reference data — safe to dump into seed.sql.
SEED_TABLES = ("meters", "poets")


def _sqlite_literal(value):
    """Render a Python value into a SQLite-safe SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bytes):
        return "X'" + value.hex() + "'"
    # Default: TEXT. Escape single quotes by doubling them.
    return "'" + str(value).replace("'", "''") + "'"


def dump_schema(con: sqlite3.Connection) -> str:
    """All DDL — CREATE TABLE / INDEX / TRIGGER / VIEW, in roughly the
    order sqlite_master lists them (which respects dependencies)."""
    lines = [
        "-- Padyarchana schema dump",
        "-- Regenerate with: ./venv/bin/python scripts/dump_db.py",
        "",
        "PRAGMA foreign_keys = OFF;",
        "BEGIN TRANSACTION;",
        "",
    ]
    rows = con.execute(
        """
        SELECT type, name, tbl_name, sql FROM sqlite_master
        WHERE sql IS NOT NULL
          AND name NOT LIKE 'sqlite_%'
        ORDER BY
          CASE type
            WHEN 'table'   THEN 1
            WHEN 'index'   THEN 2
            WHEN 'trigger' THEN 3
            WHEN 'view'    THEN 4
            ELSE 5
          END,
          name
        """
    ).fetchall()
    for kind, name, _tbl, sql in rows:
        if not sql:
            continue
        lines.append(f"-- {kind}: {name}")
        lines.append(sql.strip().rstrip(";") + ";")
        lines.append("")
    lines += ["COMMIT;", "PRAGMA foreign_keys = ON;", ""]
    return "\n".join(lines)


def dump_seed(con: sqlite3.Connection) -> str:
    """INSERT statements for the small reference tables only."""
    lines = [
        "-- Padyarchana seed data (reference rows only — NO poems).",
        "-- Run after schema.sql; then run scripts/import_json.py over",
        "-- padyalu_json_data/*.json to repopulate poems.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for table in SEED_TABLES:
        cols = [r[1] for r in con.execute(f"PRAGMA table_info({table})")]
        if not cols:
            lines.append(f"-- (table {table} has no columns; skipping)")
            continue
        col_list = ", ".join(cols)
        rows = con.execute(
            f"SELECT {col_list} FROM {table} ORDER BY id"
        ).fetchall()
        lines.append(f"-- {table}: {len(rows)} rows")
        for row in rows:
            literals = ", ".join(_sqlite_literal(v) for v in row)
            lines.append(f"INSERT INTO {table} ({col_list}) VALUES ({literals});")
        lines.append("")
    lines += ["COMMIT;", ""]
    return "\n".join(lines)


def main():
    if not DB.exists():
        print(f"DB not found: {DB}", file=sys.stderr)
        sys.exit(1)
    con = sqlite3.connect(DB)
    try:
        SCHEMA_OUT.write_text(dump_schema(con), encoding="utf-8")
        SEED_OUT.write_text(dump_seed(con), encoding="utf-8")
    finally:
        con.close()
    print(f"wrote {SCHEMA_OUT} ({SCHEMA_OUT.stat().st_size:,} bytes)")
    print(f"wrote {SEED_OUT}   ({SEED_OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
